package:
  name: percolation
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"
source:
  path: ../../
build:
  number: 1
requirements:
  build:
  - python
  - pip
  - setuptools >=61.0
  - versioningit~=2.0
  run:
  - python
  - pip
  - setuptools >=61.0
  - versioningit~=2.0
  - numpy
  - matplotlib
  - seaborn
about:
  home: https://uibcdf.org
  license: MIT License
  summary: ''
  description: 'This library generates random passwords with options to add numbers
    or special characters. '
  dev_url: https://github.com/Ericko1195/Contrasenias.git
  doc_url: https://github.com/Ericko1195/Contrasenias.git
